### ISSUE TITLE
Config reading error: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by mohaEs** [justusschock/shapenet#14]
Hi.
when I am trying to train the network, I have got the following error.
Do you have any tips?

conda 
python 3.6
PyYAML 5.1

AttributeError: 'str' object has no attribute 'items'
`  for doc in docs:
Traceback (most recent call last):
  File "./scripts/train_single_shapenet.py", line 143, in <module>
    train_shapenet()
  File "./scripts/train_single_shapenet.py", line 38, in train_shapenet
    config_dict = config(os.path.abspath(args.config))
  File "C:\Users\User\Anaconda3\envs\Env_python3_shapenet\lib\site-packages\shapenet\utils\load_config_file.py", line 54, in __call__
    for key, vals in group_dict.items():
AttributeError: 'str' object has no attribute 'items'`

**Comment by justusschock** [comment]
Can you show me your configuration YAML (you can also replace all paths and names to dummy ones, if you want to...)? My first wild guess would be, that there is a level of indentation missing.

**Comment by mohaEs** [comment]
yup. you are right.
the problem was in the configuration file.
Now I used your share example config file and is working.
Thanks.

Now, I have the following error which is not related to this issue. could you please kindly let me know what is the reason?

`  for doc in docs:
Number of Parameters: 6248029
Save Path already exists. Saved Models may be overwritten
cuda:0
Load Data
Traceback (most recent call last):
  File "./scripts/train_single_shapenet.py", line 143, in <module>
    train_shapenet()
  File "./scripts/train_single_shapenet.py", line 85, in train_shapenet
    random_offset=config_dict["data"]["offset_train"]
  File "C:\Users\User\Anaconda3\envs\Env_python3_shapenet\lib\site-packages\shapedata\single_shape\dataset.py", line 144, in __init__
    LMK_EXTENSIONS)
TypeError: __init__() takes 3 positional arguments but 5 were given`

**Comment by justusschock** [comment]
It seems, like your version of `delira`is too new. You need version 0.3.1 or below, because there was a major data-API refactoring
