### ISSUE TITLE
A trainging problem

### ISSUE THREAD

**Issue by LilioISnotAfox** [justusschock/shapenet#15]
After run the train_single_shapenet.py ,it returns a attribute error like this:
Traceback (most recent call last):
  File "scripts/train_single_shapenet.py", line 144, in <module>
    train_shapenet()
  File "scripts/train_single_shapenet.py", line 19, in train_shapenet
    from delira.training import PyTorchNetworkTrainer
  File "~/anaconda3/lib/python3.6/site-packages/delira/training/__init__.py", line 2, in <module>
    from .experiment import AbstractExperiment
  File "~/anaconda3/lib/python3.6/site-packages/delira/training/experiment.py", line 7, in <module>
    from ..models import AbstractNetwork
  File "~/anaconda3/lib/python3.6/site-packages/delira/models/__init__.py", line 7, in <module>
    from .classification import VGG3DClassificationNetworkPyTorch, \
  File "~/anaconda3/lib/python3.6/site-packages/delira/models/classification/__init__.py", line 8, in <module>
    from .classification_network_tf import ClassificationNetworkBaseTf
  File "~/anaconda3/lib/python3.6/site-packages/delira/models/classification/classification_network_tf.py", line 5, in <module>
    from delira.models.classification.ResNet18 import ResNet18
  File "~/anaconda3/lib/python3.6/site-packages/delira/models/classification/ResNet18.py", line 6, in <module>
    relu = tf.keras.layers.ReLU
AttributeError: module 'tensorflow.keras.layers' has no attribute 'ReLU'

How can I solve this problem?

**Comment by justusschock** [comment]
I don't know, what you're trying to do. It seems like you try to run the model with tensorflow backend which will obviously not work, since this model is pytorch-only.
