### ISSUE TITLE
error for prediction: reading weights

### ISSUE THREAD

**Issue by mohaEs** [justusschock/shapenet#16]
**hi

My model is trained but when I am using the predict_from_net.py with the wieghts, 
checkpoint_best.pth, 
I am getting following errors. Is there any suggestions?
Thanks in advance.**

``` 
for doc in docs:
Traceback (most recent call last):
  File "./scripts/predict_from_net.py", line 35, in predict
    net = torch.jit.load(os.path.abspath(args.weight_file))
  File "C:\Users\User\Anaconda3\envs\Env_python36_shapenet\lib\site-packages\torch\jit\__init__.py", line 146, in load
    torch._C.import_ir_module(module_lookup, f, map_location, _extra_files)
RuntimeError: [enforce fail at ..\caffe2\serialize\inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed
finding central directory
(no backtrace available)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/predict_from_net.py", line 60, in predict
    os.path.abspath(args.weight_file))["state_dict"]["model"])
KeyError: 'state_dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./scripts/predict_from_net.py", line 139, in <module>
    predict()
  File "./scripts/predict_from_net.py", line 62, in predict
    net.load_state_dict(torch.load(os.path.abspath(args.weight_file)))
  File "C:\Users\User\Anaconda3\envs\Env_python36_shapenet\lib\site-packages\torch\nn\modules\module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ShapeNetwork:
        Missing key(s) in state_dict: "_out_layer._indices_shape_params", "_out_layer._indices_homogen_params", "_out_layer._shape_layer._layer._shape_mean", "_out_layer._shape_layer._layer._shape_components", "_out_layer._homogen_trafo._indices_scale_params", "_out_layer._homogen_trafo._indices_rotation_params", "_out_layer._homogen_trafo._indices_translation_params", "_out_layer._homogen_trafo._layer._trafo_matrix", "_model.model.conv_1._conv.weight", "_model.model.conv_1._conv.bias", "_model.model.conv_2._conv.weight", "_model.model.conv_2._conv.bias", "_model.model.down_conv_1._conv.weight", "_model.model.down_conv_1._conv.bias", "_model.model.conv_3._conv.weight", "_model.model.conv_3._conv.bias", "_model.model.conv_4._conv.weight", "_model.model.conv_4._conv.bias", "_model.model.down_conv_2._conv.weight", "_model.model.down_conv_2._conv.bias", "_model.model.conv_5._conv.weight", "_model.model.conv_5._conv.bias", "_model.model.conv_6._conv.weight", "_model.model.conv_6._conv.bias", "_model.model.down_conv_3._conv.weight", "_model.model.down_conv_3._conv.bias", "_model.model.conv_7._conv.weight", "_model.model.conv_7._conv.bias", "_model.model.conv_8._conv.weight", "_model.model.conv_8._conv.bias", "_model.model.down_conv_4._conv.weight", "_model.model.down_conv_4._conv.bias", "_model.model.conv_9._conv.weight", "_model.model.conv_9._conv.bias", "_model.model.conv_10._conv.weight", "_model.model.conv_10._conv.bias", "_model.model.conv_11._conv.weight", "_model.model.conv_11._conv.bias", "_model.model.conv_12._conv.weight", "_model.model.conv_12._conv.bias", "_model.model.final_conv.weight", "_model.model.final_conv.bias".
        Unexpected key(s) in state_dict: "optimizer", "model", "epoch".
```

**Comment by justusschock** [comment]
I think I fixed this on master. Can you try to pull/reinstall the repo and try again?

I think the problem was, that I assumed the checkpoint to be a dict of either
```python
{
    "state_dict": {
        "model": {
            ... # model state
        },
        "optimizer": {
           ... # optimizer state
        }
    ... # other misc stuff
}
```

or of 

```python
{
    ... # model state
}
```

but in reality it was of type 

```python
{
    "model": {
        ... # model state
    },
    "optimizer": {
       ... # optimizer state
    }
... # other misc stuff
}
```.

This has been changed a while ago and I forgot to update this here. Sorry!

**Comment by mohaEs** [comment]
I have also created my own predict_from_net.py by removing the try catches and also making the strict=False in net.load_state_dict. Now it is working.
I also attached it here.

[predict_from_net.py.txt](https://github.com/justusschock/shapenet/files/3162220/predict_from_net.py.txt)

**Comment by justusschock** [comment]
**This might not throw errors, but this won't work correctly.**

The problem is, that `load_state_dict` is unable to find the correct keys, but with `strict=False` it will simply ignore them and *not load the weights at all*. I'm afraid, there is no other way, than switching to the correct resolution as I did.

**Comment by mohaEs** [comment]
Ok. surprisingly, the results are reasonable. 
Sure. If I got any problem I will try your method.

![297461011_1](https://user-images.githubusercontent.com/16600369/57456025-d6f62200-726c-11e9-8f41-93dfe4cc2a1a.png)

**Comment by justusschock** [comment]
The results are not reasonable at all... Only the groundtruth is reasonable (since it is not changed), but the predictions are only the orange points, which are not reasonable at all

**Comment by mohaEs** [comment]
Yes. you are right. it is not reasonable. I am going to try your method. and let you know the results.

**Comment by mohaEs** [comment]
Yup. Now loading is ok and prediction works. Thanks.
But FYI, just there was a simple error:
error in line 59, predict_from_net.py.  a ')' is missed.

**Comment by justusschock** [comment]
Thanks. fixed it.
