### ISSUE TITLE
error while training

### ISSUE THREAD

**Issue by viliusmat** [justusschock/shapenet#27]
Hello, during training in validation step I get this error. Any ideas what is happening?
Epoch 1: 100%|████████████████████████████| 689/689 [03:18<00:00,  3.75 batch/s]
Validate:   0%|                                    | 0/689 [00:00<?, ? sample/s]Traceback (most recent call last):
  File "shapenet/scripts/train_single_shapenet.py", line 149, in <module>
    train_shapenet()
  File "shapenet/scripts/train_single_shapenet.py", line 145, in train_shapenet
    val_score_mode='lowest')
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/base_trainer.py", line 444, in train
    verbose=verbose))
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 291, in predict_data_mgr_cache_metrics_only
    cache_preds=False, **kwargs)
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 399, in predict_data_mgr_cache
    **kwargs):
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 219, in predict_data_mgr
    preds = self.predict(copy.copy(batch_dict), **kwargs)
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 138, in predict
    **pred
TypeError: convert_torch_tensor_to_npy() argument after ** must be a mapping, not Tensor

**Comment by justusschock** [comment]
I'll have a look at that, thanks for reporting it

**Comment by justusschock** [comment]
I should have resolved this issue by now. This was a failure during the upgrade to delira-0.4.1

**Comment by viliusmat** [comment]
Thank you for your quick response. Now I get the following error:
Epoch 0: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1999/1999 [24:49<00:00,  1.28 batch/s]
Validate:   0%|                                                                                                                             | 0/330 [00:00<?, ? sample/s]Traceback (most recent call last):
  File "train_single_shapenet.py", line 147, in <module>
    train_shapenet()
  File "train_single_shapenet.py", line 143, in train_shapenet
    val_score_mode='lowest')
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/base_trainer.py", line 444, in train
    verbose=verbose))
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 291, in predict_data_mgr_cache_metrics_only
    cache_preds=False, **kwargs)
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 399, in predict_data_mgr_cache
    **kwargs):
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 232, in predict_data_mgr
    metric_keys=metric_keys)
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 555, in calc_metrics
    for key, metric_fn in metrics.items()}
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/delira/training/predictor.py", line 555, in <dictcomp>
    for key, metric_fn in metrics.items()}
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/sklearn/metrics/regression.py", line 241, in mean_squared_error
    y_true, y_pred, multioutput)
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/sklearn/metrics/regression.py", line 78, in _check_reg_targets
    y_true = check_array(y_true, ensure_2d=False)
  File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/sklearn/utils/validation.py", line 539, in check_array
    % (array.ndim, estimator_name))
ValueError: Found array with dim 3. Estimator expected <= 2.

**Comment by viliusmat** [comment]
Hello one more time. I am very bad at Python, so I think it is stupid to do what I did :) I edited regression.py in sklearn source code to accept multidimensional arrays:
y_true = check_array(y_true, ensure_2d=False, allow_nd=True)
y_pred = check_array(y_pred, ensure_2d=False, allow_nd=True)

After that The code was able to complete the Validation step, but I got another error at the beginning of next epoch. I'm pasting just the last line:

File "/home/vilius/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/core/_methods.py", line 85, in _mean
    ret = ret.dtype.type(ret / rcount)

So I replaced the return statement in shape_network.py:
return metric_vals, loss_vals, {k: v.detach() for k, v in preds.items()}

with this one:

return {k: v.cpu().detach().numpy() for k, v in metric_vals.items()}, {k: v.cpu().detach().numpy() for k, v in loss_vals.items()}, {k: v.detach() for k, v in preds.items()}


Now I am trying to train on 100 images just to see if there is no more errors.
Sorry for such a messy post.
